### ISSUE TITLE
Eroor with "error.py" module

### ISSUE THREAD

**Issue by Javanoide** [FNNDSC/med2image#5]
Hello,

When i run med2image script i have this following error : 

./med2image.py -i .\MRI.nii -d out -o image.jpg -s -1
Traceback (most recent call last):
  File "med2image.py", line 30, in <module>
    from . import error
ImportError: cannot import name 'error'

When i tried to fix import error by replacing  "from . import xxxx" by " import xxxx", script output nothing.

Have you any ideas to fix that error ? 

Thanks.

**Comment by rudolphpienaar** [comment]
Please update to the latest version and try again...

**Comment by jbernal0019** [comment]
Hey Javanoide

You should now install med2image with:

`pip install med2image`

A `med2image` binary is now available after the installation. So your new code would be:

`med2image -i .\MRI.nii -d out -o image.jpg -s -1`

Notice that `med2image` has been ported to `python3` where there are important differences between dotted-relative and non-dotted-absolute imports.
